Repository gisce/enerdata, pull requests merged in 2019-10, with the labels that each got.

#124 Translate civil hour to solar hour in RE
  enerdata/datetime/solar_hour.py
  enerdata/profiles/profile.py
  spec/datetime/solar_hour_spec.py
Labels: WIP, bug, to be merged

#126 Assert no energy in periods with zero generation coefficient
  enerdata/profiles/profile.py
  spec/profiles/profile_spec.py
Labels: enhancement, release, to be merged

#127 Set setup description
  setup.py
Labels: enhancement
