Repository gisce/enerdata, pull requests merged in 2020-04, with the labels that each got.

#134 New 6x tariffs
  enerdata/contracts/tariff.py
  spec/contracts/tariff_spec.py
Labels: to be merged

#135 Fix pandas to v0.23.4 version
  requirements.txt
Labels: enhancement, to be merged

#133 Fix include csv files in packages setup
  setup.py
Labels: bug

#136 Fix mamba testing py2 support
  requirements-dev.txt
Labels: bug, to be merged

#132 Profile with flat coff
  enerdata/profiles/profile.py
  spec/profiles/profile_spec.py
Labels: enhancement, to be merged :octocat:
