Repository gisce/enerdata, pull requests merged in 2021-06, with the labels that each got.

#144 FIX potencia máxima para tarifas 6.x
  enerdata/contracts/tariff.py
  spec/contracts/tariff_spec.py
Labels: bug :bug:, to be merged :octocat:

#145 Se han añadido periodos de potencia a las tarifas de vehículo eléctrico
  enerdata/contracts/tariff.py
  spec/contracts/tariff_spec.py
  spec/profiles/profile_spec.py
Labels: bug :bug:

#146 Perfilador universal de 1 período de energía y correcciones en la obtención de perfiles para PVPC
  enerdata/contracts/tariff.py
  enerdata/profiles/profile.py
Labels: deployed, enhancement, to be merged :octocat:
